/**
 * Regenerates the results section of docs/benchmarks/redaction.md and writes
 * docs/benchmarks/redaction.json from the synthetic redaction test set.
 *
 *   npx tsx packages/core/scripts/redaction-report.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';
import { evaluate, type CategoryScore, type EvalReport } from '../src/redaction/eval/evaluate';
import { buildDataset, DEFAULT_SEED } from '../src/redaction/eval/synthetic';

const HELD_OUT_SEED = 7;
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const mdPath = resolve(root, 'docs/benchmarks/redaction.md');
const jsonPath = resolve(root, 'docs/benchmarks/redaction.json');

const pct = (x: number | null) => (x === null ? 'n/a' : (x * 100).toFixed(1));

function table(rows: CategoryScore[]): string {
  const head =
    '| Category | Support | TP | FP | FN | Precision % | Recall % | F1 % |\n|---|---:|---:|---:|---:|---:|---:|---:|';
  return [
    head,
    ...rows.map(
      (c) =>
        `| ${c.type} | ${c.support} | ${c.tp} | ${c.fp} | ${c.fn} | ${pct(c.precision)} | ${pct(c.recall)} | ${pct(c.f1)} |`,
    ),
  ].join('\n');
}

function section(title: string, seed: number, r: EvalReport): string {
  const misses = r.recallByGroup.filter((g) => g.recall < 1);
  return [
    `### ${title} (seed ${seed})`,
    '',
    `${r.samples} samples: ${r.positives} with at least one sensitive span, ${r.negatives} hard negatives. ` +
      `Negative samples with any redaction: ${r.negativeSamplesFlagged}.`,
    '',
    table([...r.categories, r.any]),
    '',
    misses.length === 0
      ? 'Every generator group reached 100% recall.'
      : [
          'Groups below 100% recall:',
          '',
          '| Group | Support | Recall % |',
          '|---|---:|---:|',
          ...misses.map((g) => `| ${g.group} | ${g.support} | ${pct(g.recall)} |`),
        ].join('\n'),
  ].join('\n');
}

const dev = evaluate(buildDataset({ seed: DEFAULT_SEED }));
const heldOut = evaluate(buildDataset({ seed: HELD_OUT_SEED }));

const results = [
  '<!-- results:start (generated by packages/core/scripts/redaction-report.ts, do not edit by hand) -->',
  '',
  section('Tuning set', DEFAULT_SEED, dev),
  '',
  section('Fresh draw', HELD_OUT_SEED, heldOut),
  '',
  '<!-- results:end -->',
].join('\n');

const md = readFileSync(mdPath, 'utf8');
const updated = md.replace(/<!-- results:start[\s\S]*?<!-- results:end -->/, results);
if (updated === md && !md.includes(results))
  throw new Error('results markers not found in ' + mdPath);
writeFileSync(mdPath, await format(updated, { filepath: mdPath }));

const strip = (r: EvalReport) => ({
  ...r, // Drop the texts and values so no credential-shaped string is ever committed.
  errors: r.errors.map(({ text: _t, value: _v, ...e }) => e),
});
writeFileSync(
  jsonPath,
  JSON.stringify(
    {
      generatedBy: 'packages/core/scripts/redaction-report.ts',
      runs: [
        { seed: DEFAULT_SEED, ...strip(dev) },
        { seed: HELD_OUT_SEED, ...strip(heldOut) },
      ],
    },
    null,
    2,
  ) + '\n',
);
console.info(`wrote ${mdPath} and ${jsonPath}`);
